import './globals.css'

import localFont from 'next/font/local';
import { avenirVarible } from './fonts';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={[
          avenirVarible.variable
        ].join(' ')}>
      <body className='font-primary'>{children}</body>
    </html>
  )
}



