export const initialPhrases = [
    "1 lorem 😎 ipausm dolor sit amet, consectetur adipisic",
    "2 lorem ipausm do😎lor sit amet, consectetur adipisiclorem ipausm dolor sit amet, consectetur adipisic",
    "3 lorem i😎pausm dolor ",
    "4 lorem ipa😎usm dolor sit amet, consectetur adipisiclorem ipausm dolor sit amet, consectetur adipisic",
    "5 lorem ip😎ausm dolor sit amet, consectetur adipisic",
    "6 lorem ipausm dolor s ipisic",
    "7 lorem ipausm do😎lor sit amet, consectetur adipisic",
    "8 lorem i😎pausm dolor si onsectetur adipisic",
    "9 lorem ipausm dol😎or sit amet, consectetur adipisic",
    "10 lorem ipausm dolor😎 sit amet, consectetur adipisic",
    "11 lorem ipa😎usm dolor sit amet,  sectetur adipisic",
    "12 lorem ipausm dolor s tetur adipisic",
    "13 lorem ipausm 😎dolor s t, consectetur adipisic",
    "14 lorem ip😎ausm dolor sit amet, consectetur adipisic",
    "15 lorem ipausm d😎olor sit amet, consectetur adipisic",
    "16 lorem ipausm dolor sit amet, consectetur adipisic 😎",
    "17 lorem ipausm d😎olor sit amet, conse",
    "18 lorem ipausm d😎olor sit amet, conselorem ipausm d😎olor sit amet, conse",
    "19 lorem ipausm d😎olor sit amet, conse",
    "20 lorem ipa 😎olor sit amet, conse",
    "21 lorem ipausm d😎olor sit am conse",
    "22 lorem ipausm d😎olor sit lorem ipausm d😎olor sit amet, conse",
    "23  pausm d😎olor sit amet, conse",
    "24 lorem ipa  d😎olor sit amet, conse",
  ];
